version: '3'

services:
  database:
    image: postgres:latest
    container_name: database
    hostname: database
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: DevsuBD
    ports:
      - "5432:5432"
